#! /bin/bash
#
#-------------------------------------------------------------
#---------- Camera Import and resize script ------------------
#------------------ Harry Allerston 2013 ---------------------
#-------------------------------------------------------------

user=$(whoami)
SD=$(head /home/$user/.CameraTools/SDcard)
pictures=$(head /home/$user/.CameraTools/PicturesPath)

menuoption=$(zenity --entry --title "Welcome to Camera Tools" --text "
==================================
   Camera Import Wizard v 1.3 
==================================

Select Menu Option :

1) Import JPEG images from SD card

2) Import RAW images from SD card

3) Clear SD Card

4) Edit path to SD card

5) Edit path to Pictures folder

6) Exit

=================================="
)


### Import JPEG from SD card###
if [ "$menuoption" = "1" ]; then

  	dest=$(zenity --entry --text "Name of destination folder?")
	mkdir $pictures/$dest
	mkdir $pictures/$dest/JPEG
	mkdir $pictures/$dest/EDITED
	
	find $SD -name "*.JPG" -exec cp '{}' $pictures/$dest/JPEG \; | zenity --progress --auto-kill --width 350 --pulsate --text "Copying JPEG files to   ----> $dest" --title "Camera Import"
    
    find $SD -name "*.jpg" -exec cp '{}' $pictures/$dest/JPEG \; | zenity --progress --auto-kill --width 350 --pulsate --text "Copying JPEG files to   ----> $dest" --title "Camera Import"

    zenity --info --text "Import complete!"
    
    exec camera-import-gtk
fi



### Import RAW from SD card ###
if [ "$menuoption" = "2" ]; then
  
    dest=$(zenity --entry --text "Name of destination folder?")	
	mkdir $pictures/$dest
	mkdir $pictures/$dest/RAW
	mkdir $pictures/$dest/EDITED
	find $SD -name "*.RAF" -exec cp '{}' $pictures/$dest/RAW \; | zenity --progress --auto-kill --width 350 --pulsate --text "Copying  files to   ----> $dest" --title "Camera Import"
    zenity --info --text "Import complete!"
    exec camera-import-gtk
fi



## Clear SD card ##
if [ "$menuoption" = "3" ]; then
    rm -r $SD/* | zenity --progress --width 350 --auto-kill --pulsate --text "Clearing SD Card" --title "Camera Import"
	exec camera-import-gtk
fi



## Edit path to SD card ##
if [ "$menuoption" = "4" ]; then
    SD=$(zenity --title "Select Path to SD card" --file-selection --directory)
    echo $SD > /home/$user/.CameraTools/SDcard
	exec camera-import-gtk
fi


## Edit path to Pictures folder ##
if [ "$menuoption" = "5" ]; then
	SD=$(zenity --title "Select Path to Pictures folder" --file-selection --directory)
    echo $SD > /home/$user/.CameraTools/PicturesPath	
	exec camera-import-gtk
fi


## Exit Program ##
if [ "$menuoption" = "6" ]; then
	exit
fi



